로그인 UI구현
AppCenter-iOS-15th/yongheon pull request #1
Opened 2023-04-11 11:04 UTC by rrheon

로그인 UI구현

2023-04-11 12:00 UTC, nomatterjun commented
와우.. 너무 잘했는데..
레벨을 좀 높여도 될지도.. 🤔

2023-04-11 12:37 UTC, nomatterjun commented
## 1. lazy var

``` Swift
private let passwordTextField: UITextField = {
  // ...
  tf.addTarget(self, action: #selector(textFieldEditingChanged(_:)), for: .editingChanged)
  return tf
}
```

이 부분 `self`를 참조하고 있어서 경고가 발생하고 있는데
(원래는 에러가 발생하겠는데 `selector`라서 허용은 되는 것 같아)
클로저 내부에서 `self`를 참조할때는 `lazy var`로 선언해주는게 좋아!

## 2. UIButton Configuration

``` Swift
private let loginButton: UIButton = {
var config = UIButton.Configuration.filled()
config.title = "LOG IN"
let btn = UIButton(configuration: config)
btn.configurationUpdateHandler = { btn in
  switch btn.state {
  case .normal:
    btn.configuration?.baseBackgroundColor = UIColor(red: 0.64, green: 0.53, blue: 0.32, alpha: 1.00)
  case .disabled:
    btn.configuration?.baseBackgroundColor = UIColor(red: 0.20, green: 0.16, blue: 0.04, alpha: 1.00)
  default: break
  }
}
btn.layer.cornerRadius = 15
btn.clipsToBounds = true
return btn
}()
```

이렇게 설정해주면
``` Swift
loginButton.isEnabled = true
```

만 해줘도 버튼의 `state`에 따라서 UI의 변화를 만들어줄 수 있어!
한 번 시도해보면 좋을듯..!

2023-04-11 15:04 UTC, rrheon commented
> ## 1. lazy var
> ```swift
> private let passwordTextField: UITextField = {
>   // ...
>   tf.addTarget(self, action: #selector(textFieldEditingChanged(_:)), for: .editingChanged)
>   return tf
> }
> ```
> 
> 이 부분 `self`를 참조하고 있어서 경고가 발생하고 있는데 (원래는 에러가 발생하겠는데 `selector`라서 허용은 되는 것 같아) 클로저 내부에서 `self`를 참조할때는 `lazy var`로 선언해주는게 좋아!
> 
> ## 2. UIButton Configuration
> ```swift
> private let loginButton: UIButton = {
> var config = UIButton.Configuration.filled()
> config.title = "LOG IN"
> let btn = UIButton(configuration: config)
> btn.configurationUpdateHandler = { btn in
>   switch btn.state {
>   case .normal:
>     btn.configuration?.baseBackgroundColor = UIColor(red: 0.64, green: 0.53, blue: 0.32, alpha: 1.00)
>   case .disabled:
>     btn.configuration?.baseBackgroundColor = UIColor(red: 0.20, green: 0.16, blue: 0.04, alpha: 1.00)
>   default: break
>   }
> }
> btn.layer.cornerRadius = 15
> btn.clipsToBounds = true
> return btn
> }()
> ```
> 
> 이렇게 설정해주면
> 
> ```swift
> loginButton.isEnabled = true
> ```
> 
> 만 해줘도 버튼의 `state`에 따라서 UI의 변화를 만들어줄 수 있어! 한 번 시도해보면 좋을듯..!

참고해서 수정해볼게🙂

2023-04-11 15:05 UTC, rrheon commented
참고해서 수정해볼게!🙂

2023-04-12 00:34 UTC, eung7 requested changes
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

2023-04-12 00:34 UTC, EnnzoKim commented on ToDoApp/ViewController.swift
![image](https://user-images.githubusercontent.com/97531269/231315694-a4f1f390-856b-4762-af2c-0a7cf9089c01.png)

위와 같이 `TextField`를 구현하면 `Placeholder`가 `leftPadding`이 `0`이라서 어색해 보일 수 있어 ! 
따로 커스텀을 주어서 `leftPadding` 값을 줘보는 것도 괜찮을 것 같아!

https://developer-fury.tistory.com/46

2023-04-12 00:34 UTC, eung7 commented on ToDoApp/ViewController.swift
>          view.addSubview(loginLabel)
```suggestion
      [
        emailTextField,
        loginLabel,
        passwordTextField,
        loginButton,
        registerButton,
        forgotPasswordButton,
        forgotPasswordImageView
      ].forEach {
        view.addSubview($0)
      }
```

이런 식으로 `.forEach` 구문을 이용하면 중복된 코드를 지울 수 있어서 편리할거야!

2023-04-12 00:34 UTC, eung7 commented on ToDoApp/ViewController.swift
```swift
extension ViewController: UITextFieldDelegate {
  @objc func textFieldEditingChanged(_ textField : UITextField) {
    if textField.text?.count == 1 {
      if textField.text?.first == " " {
        textField.text = ""
        return
      }
    }
    guard
      let email = emailTextField.text, !email.isEmpty,
      let password = passwordTextField.text, !password.isEmpty else {
      loginButton.backgroundColor = UIColor(red: 0.20, green: 0.16, blue: 0.04, alpha: 1.00)
      loginButton.isEnabled = false
      return
    }
    loginButton.backgroundColor = UIColor(red: 0.64, green: 0.53, blue: 0.32, alpha: 1.00)
    loginButton.isEnabled = true
  }
}
```

지금 `Selector`가 `PasswordTextField` 밖에 등록이 되어있지 않아서
`Password`가 입력되어 있는 상태에서 `Email`을 지우면 여전히 로그인 버튼이 활성화가 되어있어!
그래서 `Selector`를 이용하여 `Email`과 `Password`의 값이 `empty`인지 판단해주는 `isValidated` 라는 `Boolean` 타입을 이용하여 판단하는 것도 생각해보면 좋을 것 같아 !


많은 방법이 있겠지만, `Property Observer`를 이용하는 것도 좋은 방법일 수도 있겠다는 생각이 들어 ~!

2023-04-12 00:37 UTC, eung7 commented on ToDoApp/ViewController.swift
```swift
final class LoginVIewController: UIViewController {
}    
```

더 이상 상속을 받지 않을 `class`라면 `final`을 붙여줘서 메모리 효율을 높여주는 게 좋은 방법이야!

그리고 나중에 `UIViewController`가 추가 될 것 같으니까 `LoginViewController`같이 네이밍을 적절하게 바꿔주면 좋을 것 같아 !

2023-04-12 03:17 UTC, rrheon commented on ToDoApp/ViewController.swift
수정해볼게!!🙂

2023-04-27 03:30 UTC, merged