Dev
AppCenter-iOS-15th/yongheon pull request #4
Opened 2023-05-25 03:16 UTC by rrheon

구조체 -> 코어데이터로 변경, 오른쪽으로 스와이프기능 추가
완료여부에 따라 section 구분

2023-05-25 16:25 UTC, nomatterjun requested changes

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/View/CustomCell.swift
> +  }
`todoData` 프로퍼티에 `didSet` 옵저버를 통해 `configureUIWithData` 메서드를 호출해주고 있는 건 너무 좋은 아이디어인 것 같아!

다만 이럴 때는 외부에서 `CustomCell`을 핸들링할 수 있는 부분이 
1. `todoData` 프로퍼티
2. `configureUIWithData`
이렇게 두 군데가 되기 때문에 외부에서 사용될 경우에 통일성이 지켜지지 못할 수 있어.

`configureUIWithData`에 `private` 접근 제어자를 사용해줘서 내부 scope에서만 사용할 수 있도록 해주면 좋을 것 같아!

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Controllers/AddItemViewController.swift
> +final class AddItemViewController: UIViewController, UIScrollViewDelegate {
`UITextViewDelegate`를 `extension`으로 분리해준 것 처럼 `UIScrollViewDelegate`도 분리해주면 좋을 것 같아!

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Extention/UITextViewExtention.swift
> +  }
```suggestion
  func nonEmpty() -> String? {
    if self.isEmpty { return nil }
    return self.text
  }
```

이 부분 같은 경우는 `extension` 사용의 이점을 활용하지 못하고 있어.
`self`를 통해서 인스턴스의 프로퍼티에 접근할 수 있는 점을 활용해주도록 해줘!

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Controllers/AddItemViewController.swift
> +    if let itemToEdit = itemToEdit {
이 부분처럼 아래에서 계속해서 쓰이는 데이터이면서 `else` 구문이 없을 경우에는
`guard let` 구문을 사용해주면 indent를 줄일 수 있어!

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Controllers/AddItemViewController.swift
>      }
혹시 이 부분은 `mainVC`를 탐색해서 `pop` 시켜준 특별한 이유가 있을까?

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Controllers/MainViewController.swift
전반적으로 `getToDoList` 메서드가 너무 자주 호출되고 있는 느낌이 있어!
DB나 서버에서 데이터를 불러오는 작업은 비교적 무거운 작업일 때가 많기 때문에 가능하다면 최소화해주는 게 좋아.
(실시간으로 변동이 잦은 값이라면 불가능하겠지만..)

`viewWillAppear`에서 호출한 `getToDoList`의 데이터를 조금 더 적극적으로 활용해주면 어떨까?

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Controllers/MainViewController.swift
> +        self.updateItemStatus()
위에서 GCD를 사용해서 비동기처리를 해주었던데 여기도 똑같이 적용해줘!

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Models/CoreDataManager.swift
`@escaping` 클로저들을 활용해준 것 아주 굿..! 👍👍

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Extention/DateExtenstion.swift
> +  func convertDateToString(date: Date) -> String {
```suggestion
  func toString() -> String {
```

`extension`에서 함수를 정의해주는 경우 사용해줄 때
`today.convertDateToString()`와 같이 사용되면 이미 앞에 명사가 붙어있는 거잖아?
그래서 간단하게 `toString()`처럼 함수 이름을 정해주면
`today.toString()`처럼 코드 가독성이 좋아져!

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Extention/DateExtenstion.swift
> +  func convertDateToString(date: Date) -> String {
그리고 여기도 마찬가지로 `self` 활용해줘..!

2023-05-25 16:25 UTC, nomatterjun commented on ToDoApp/Models/CoreDataManager.swift
> +  }
이런 에러가 발생할 수 있는 작업을 다룰 때에는 UI 레이어에서 에러가 발생했는지 여부에 따라 이벤트를 처리할 수 있도록 throwing 함수로 만들어주면 좋을 것 같아

`catch`에서 `print`로 끝내는게 아니라 다시 한번 `throw`로 에러를 던져주는거지

```suggestion
  func getToDoList() throws -> [ToDoData] {
    var toDoList: [ToDoData] = []
    // 임시저장소 있는지 확인
    if let context = context {
      let request = NSFetchRequest<NSManagedObject>(entityName: self.modelName)
      // 정렬순서를 정해서 넘겨줌
      let dateOrder = NSSortDescriptor(key: "date", ascending: true)
      request.sortDescriptors = [dateOrder]
      
      do {
        // 임시저장소에서 데이터 가져오기 (fetch메서드)
        if let fetchedToDoList = try context.fetch(request) as? [ToDoData] {
          toDoList = fetchedToDoList
        }
      } catch {
        print("가져오는 것 실패")
        throw(error)
      }
    }
    
    return toDoList
  }
```

이런 느낌으로..!

그러면 UI 레이어에서

``` Swift
do {
  let todo = try todoManager.getToDoList()
} catch {
  // 에러 메시지 팝업
}
```

이렇게 에러가 발생했다는 걸 화면에 표현해줄 수 있으니까!

2023-05-26 03:57 UTC, rrheon commented on ToDoApp/Controllers/AddItemViewController.swift
>      }
기존에 AdditemViewContrller에서 Done을 누르면 MainViewController로 돌아가지 않아서 Done을 누르면 MainViewController로 돌아가고 그 전에 있던 view는 pop하는 방식으로 사용한건데 코멘트 달아준거 보고 굳이 그럴 필요가 없다고 생각했어!
기존의 func addItem() 매서드 마지막에 다음과 같은 코드로 이전 화면로 돌아가게 수정하려고해
`    navigationController?.popViewController(animated: true)`

2023-05-26 04:01 UTC, nomatterjun commented on ToDoApp/Controllers/AddItemViewController.swift
>      }
굿! 👍

2023-05-29 12:10 UTC, merged